# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               sethetter.com
tagline:             'Code, web and Wichita'
description:         'Stuff by Seth'
url:                 http://sethetter.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Seth Etter
  url:               https://twitter.com/sethetter
  email:             sethetter@gmail.com

# Custom vars
version:             1.0.0
